#ifndef MPT_IS_EMPTY_ARGS_H
#define MPT_IS_EMPTY_ARGS_H

#include "./ArgsCount.h"

#define INTERNAL_MPT_IE_COMPOSE( A, B ) A B
#define INTERNAL_MPT_IE_COMPOSE2( A, B ) A B
#define INTERNAL_MPT_IE_COMPOSE3( A, B ) A B
#define INTERNAL_MPT_IE_COMPOSE4( A, B ) A B

#define INTERNAL_MPT_IE_DELAY( ... ) __VA_ARGS__
#define INTERNAL_MPT_IE_DELAYED_COMPOSE_INNER(macro, args) INTERNAL_MPT_IE_COMPOSE( macro, args )
#define INTERNAL_MPT_IE_DELAYED_COMPOSE(macro, args) INTERNAL_MPT_IE_DELAYED_COMPOSE_INNER( macro, INTERNAL_MPT_IE_DELAY(args) )

#define INTERNAL_MPT_IE_DELAY2( ... ) __VA_ARGS__
#define INTERNAL_MPT_IE_DELAYED_COMPOSE_INNER2(macro, args) INTERNAL_MPT_IE_COMPOSE2( macro, args )
#define INTERNAL_MPT_IE_DELAYED_COMPOSE2(macro, args) INTERNAL_MPT_IE_DELAYED_COMPOSE_INNER2( macro, INTERNAL_MPT_IE_DELAY2(args) )

#define INTERNAL_MPT_IE_MULTI_CONCAT( A, ... ) A ## __VA_ARGS__
#define INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT_INNER(A, ...) INTERNAL_MPT_IE_MULTI_CONCAT(A, __VA_ARGS__)
#define INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT(A, ...) INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT_INNER(A, __VA_ARGS__)

#define INTERNAL_MPT_IE_MULTI_CONCAT2( A, ... ) A ## __VA_ARGS__
#define INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT_INNER2(A, ...) INTERNAL_MPT_IE_MULTI_CONCAT2(A, __VA_ARGS__)
#define INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT2(A, ...) INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT_INNER2(A, __VA_ARGS__)

#define MPT_ARE_ARGS_EMPTY( ... ) \
    INTERNAL_MPT_IE_DELAYED_COMPOSE \
    ( \
        INTERNAL_MPT_GET_COUNT2, \
        ( \
            INTERNAL_MPT_IE_COMPOSE3 \
            ( \
                INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT \
                ( \
                    INTERNAL_MPT_EXPAND_, \
                    INTERNAL_MPT_PROTECT_FIRST_ARG_PARENS __VA_ARGS__ \
                ), \
                () \
            ), \
            EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
        ) \
    )

#define INTERNAL_MPT_ARE_ARGS_EMPTY( ... ) \
    INTERNAL_MPT_IE_DELAYED_COMPOSE2 \
    ( \
        INTERNAL_MPT_GET_COUNT3, \
        ( \
            INTERNAL_MPT_IE_COMPOSE4 \
            ( \
                INTERNAL_MPT_IE_DELAYED_MULTI_CONCAT2 \
                ( \
                    INTERNAL_MPT_EXPAND_, \
                    INTERNAL_MPT_PROTECT_FIRST_ARG_PARENS __VA_ARGS__ \
                ), \
                () \
            ), \
            EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
            NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, NOT_EMPTY, \
        ) \
    )

#endif
