#ifndef MPT_MISCELLANEOUS_H
#define MPT_MISCELLANEOUS_H

#define MPT_CONCAT( A, B ) A ## B
#define MPT_CONCAT2( A, B ) A ## B
#define MPT_CONCAT3( A, B ) A ## B
#define MPT_CONCAT4( A, B ) A ## B
#define MPT_CONCAT5( A, B ) A ## B
#define MPT_CONCAT6( A, B ) A ## B
#define MPT_CONCAT7( A, B ) A ## B
#define MPT_CONCAT8( A, B ) A ## B
#define MPT_CONCAT9( A, B ) A ## B
#define MPT_CONCAT10( A, B ) A ## B
#define MPT_CONCAT11( A, B ) A ## B
#define MPT_CONCAT12( A, B ) A ## B
#define MPT_CONCAT13( A, B ) A ## B
#define MPT_CONCAT14( A, B ) A ## B
#define MPT_CONCAT15( A, B ) A ## B
#define MPT_CONCAT16( A, B ) A ## B
#define MPT_CONCAT17( A, B ) A ## B
#define MPT_CONCAT18( A, B ) A ## B
#define MPT_CONCAT19( A, B ) A ## B
#define MPT_CONCAT20( A, B ) A ## B

#define MPT_COMPOSE( A, B ) A B
#define MPT_COMPOSE2( A, B ) A B
#define MPT_COMPOSE3( A, B ) A B
#define MPT_COMPOSE4( A, B ) A B
#define MPT_COMPOSE5( A, B ) A B
#define MPT_COMPOSE6( A, B ) A B
#define MPT_COMPOSE7( A, B ) A B
#define MPT_COMPOSE8( A, B ) A B
#define MPT_COMPOSE9( A, B ) A B
#define MPT_COMPOSE10( A, B ) A B
#define MPT_COMPOSE11( A, B ) A B
#define MPT_COMPOSE12( A, B ) A B
#define MPT_COMPOSE13( A, B ) A B
#define MPT_COMPOSE14( A, B ) A B
#define MPT_COMPOSE15( A, B ) A B
#define MPT_COMPOSE16( A, B ) A B
#define MPT_COMPOSE17( A, B ) A B
#define MPT_COMPOSE18( A, B ) A B
#define MPT_COMPOSE19( A, B ) A B
#define MPT_COMPOSE20( A, B ) A B

#define MPT_DELAYED_CONCAT(A, B) MPT_COMPOSE(MPT_CONCAT, (A, B))
#define MPT_DELAYED_CONCAT2(A, B) MPT_COMPOSE2(MPT_CONCAT2, (A, B))
#define MPT_DELAYED_CONCAT3(A, B) MPT_COMPOSE3(MPT_CONCAT3, (A, B))
#define MPT_DELAYED_CONCAT4(A, B) MPT_COMPOSE4(MPT_CONCAT4, (A, B))
#define MPT_DELAYED_CONCAT5(A, B) MPT_COMPOSE5(MPT_CONCAT5, (A, B))
#define MPT_DELAYED_CONCAT6(A, B) MPT_COMPOSE6(MPT_CONCAT6, (A, B))
#define MPT_DELAYED_CONCAT7(A, B) MPT_COMPOSE7(MPT_CONCAT7, (A, B))
#define MPT_DELAYED_CONCAT8(A, B) MPT_COMPOSE8(MPT_CONCAT8, (A, B))
#define MPT_DELAYED_CONCAT9(A, B) MPT_COMPOSE9(MPT_CONCAT9, (A, B))
#define MPT_DELAYED_CONCAT10(A, B) MPT_COMPOSE10(MPT_CONCAT10, (A, B))
#define MPT_DELAYED_CONCAT11(A, B) MPT_COMPOSE11(MPT_CONCAT11, (A, B))
#define MPT_DELAYED_CONCAT12(A, B) MPT_COMPOSE12(MPT_CONCAT12, (A, B))
#define MPT_DELAYED_CONCAT13(A, B) MPT_COMPOSE13(MPT_CONCAT13, (A, B))
#define MPT_DELAYED_CONCAT14(A, B) MPT_COMPOSE14(MPT_CONCAT14, (A, B))
#define MPT_DELAYED_CONCAT15(A, B) MPT_COMPOSE15(MPT_CONCAT15, (A, B))
#define MPT_DELAYED_CONCAT16(A, B) MPT_COMPOSE16(MPT_CONCAT16, (A, B))
#define MPT_DELAYED_CONCAT17(A, B) MPT_COMPOSE17(MPT_CONCAT17, (A, B))
#define MPT_DELAYED_CONCAT18(A, B) MPT_COMPOSE18(MPT_CONCAT18, (A, B))
#define MPT_DELAYED_CONCAT19(A, B) MPT_COMPOSE19(MPT_CONCAT19, (A, B))
#define MPT_DELAYED_CONCAT20(A, B) MPT_COMPOSE20(MPT_CONCAT20, (A, B))

#define INTERNAL_MPT_DELAY( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY2( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY3( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY4( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY5( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY6( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY7( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY8( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY9( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY10( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY11( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY12( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY13( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY14( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY15( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY16( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY17( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY18( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY19( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY20( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY_ONE( x ) x

#define MPT_DELAY( ... ) __VA_ARGS__
#define MPT_DELAY2( ... ) __VA_ARGS__
#define MPT_DELAY3( ... ) __VA_ARGS__
#define MPT_DELAY4( ... ) __VA_ARGS__
#define MPT_DELAY5( ... ) __VA_ARGS__
#define MPT_DELAY6( ... ) __VA_ARGS__
#define MPT_DELAY7( ... ) __VA_ARGS__
#define MPT_DELAY8( ... ) __VA_ARGS__
#define MPT_DELAY9( ... ) __VA_ARGS__
#define MPT_DELAY10( ... ) __VA_ARGS__
#define MPT_DELAY11( ... ) __VA_ARGS__
#define MPT_DELAY12( ... ) __VA_ARGS__
#define MPT_DELAY13( ... ) __VA_ARGS__
#define MPT_DELAY14( ... ) __VA_ARGS__
#define MPT_DELAY15( ... ) __VA_ARGS__
#define MPT_DELAY16( ... ) __VA_ARGS__
#define MPT_DELAY17( ... ) __VA_ARGS__
#define MPT_DELAY18( ... ) __VA_ARGS__
#define MPT_DELAY19( ... ) __VA_ARGS__
#define MPT_DELAY20( ... ) __VA_ARGS__
#define MPT_DELAY_ONE( x ) x


#define MPT_DELAYED_COMPOSE(macro, args) MPT_DELAYED_COMPOSE( macro, MPT_DELAY(args) )
#define MPT_DELAYED_COMPOSE2(macro, args) MPT_DELAYED_COMPOSE2( macro, MPT_DELAY2(args) )
#define MPT_DELAYED_COMPOSE3(macro, args) MPT_DELAYED_COMPOSE3( macro, MPT_DELAY3(args) )
#define MPT_DELAYED_COMPOSE4(macro, args) MPT_DELAYED_COMPOSE4( macro, MPT_DELAY4(args) )
#define MPT_DELAYED_COMPOSE5(macro, args) MPT_DELAYED_COMPOSE5( macro, MPT_DELAY5(args) )
#define MPT_DELAYED_COMPOSE6(macro, args) MPT_DELAYED_COMPOSE6( macro, MPT_DELAY6(args) )
#define MPT_DELAYED_COMPOSE7(macro, args) MPT_DELAYED_COMPOSE7( macro, MPT_DELAY7(args) )
#define MPT_DELAYED_COMPOSE8(macro, args) MPT_DELAYED_COMPOSE8( macro, MPT_DELAY8(args) )
#define MPT_DELAYED_COMPOSE9(macro, args) MPT_DELAYED_COMPOSE9( macro, MPT_DELAY9(args) )
#define MPT_DELAYED_COMPOSE10(macro, args) MPT_DELAYED_COMPOSE10( macro, MPT_DELAY10(args) )
#define MPT_DELAYED_COMPOSE11(macro, args) MPT_DELAYED_COMPOSE11( macro, MPT_DELAY11(args) )
#define MPT_DELAYED_COMPOSE12(macro, args) MPT_DELAYED_COMPOSE12( macro, MPT_DELAY12(args) )
#define MPT_DELAYED_COMPOSE13(macro, args) MPT_DELAYED_COMPOSE13( macro, MPT_DELAY13(args) )
#define MPT_DELAYED_COMPOSE14(macro, args) MPT_DELAYED_COMPOSE14( macro, MPT_DELAY14(args) )
#define MPT_DELAYED_COMPOSE15(macro, args) MPT_DELAYED_COMPOSE15( macro, MPT_DELAY15(args) )
#define MPT_DELAYED_COMPOSE16(macro, args) MPT_DELAYED_COMPOSE16( macro, MPT_DELAY16(args) )
#define MPT_DELAYED_COMPOSE17(macro, args) MPT_DELAYED_COMPOSE17( macro, MPT_DELAY17(args) )
#define MPT_DELAYED_COMPOSE18(macro, args) MPT_DELAYED_COMPOSE18( macro, MPT_DELAY18(args) )
#define MPT_DELAYED_COMPOSE19(macro, args) MPT_DELAYED_COMPOSE19( macro, MPT_DELAY19(args) )
#define MPT_DELAYED_COMPOSE20(macro, args) MPT_DELAYED_COMPOSE20( macro, MPT_DELAY20(args) )

#define INTERNAL_MPT_CONCAT( A, B ) A ## B
#define INTERNAL_MPT_CONCAT2( A, B ) A ## B
#define INTERNAL_MPT_CONCAT3( A, B ) A ## B
#define INTERNAL_MPT_CONCAT4( A, B ) A ## B
#define INTERNAL_MPT_CONCAT5( A, B ) A ## B
#define INTERNAL_MPT_CONCAT6( A, B ) A ## B
#define INTERNAL_MPT_CONCAT7( A, B ) A ## B
#define INTERNAL_MPT_CONCAT8( A, B ) A ## B
#define INTERNAL_MPT_CONCAT9( A, B ) A ## B
#define INTERNAL_MPT_CONCAT10( A, B ) A ## B
#define INTERNAL_MPT_CONCAT11( A, B ) A ## B
#define INTERNAL_MPT_CONCAT12( A, B ) A ## B
#define INTERNAL_MPT_CONCAT13( A, B ) A ## B
#define INTERNAL_MPT_CONCAT14( A, B ) A ## B
#define INTERNAL_MPT_CONCAT15( A, B ) A ## B
#define INTERNAL_MPT_CONCAT16( A, B ) A ## B
#define INTERNAL_MPT_CONCAT17( A, B ) A ## B
#define INTERNAL_MPT_CONCAT18( A, B ) A ## B
#define INTERNAL_MPT_CONCAT19( A, B ) A ## B
#define INTERNAL_MPT_CONCAT20( A, B ) A ## B

#define INTERNAL_MPT_DELAYED_CONCAT(A, B) INTERNAL_MPT_COMPOSE(INTERNAL_MPT_CONCAT, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT2(A, B) INTERNAL_MPT_COMPOSE2(INTERNAL_MPT_CONCAT2, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT3(A, B) INTERNAL_MPT_COMPOSE3(INTERNAL_MPT_CONCAT3, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT4(A, B) INTERNAL_MPT_COMPOSE4(INTERNAL_MPT_CONCAT4, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT5(A, B) INTERNAL_MPT_COMPOSE5(INTERNAL_MPT_CONCAT5, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT6(A, B) INTERNAL_MPT_COMPOSE6(INTERNAL_MPT_CONCAT6, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT7(A, B) INTERNAL_MPT_COMPOSE7(INTERNAL_MPT_CONCAT7, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT8(A, B) INTERNAL_MPT_COMPOSE8(INTERNAL_MPT_CONCAT8, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT9(A, B) INTERNAL_MPT_COMPOSE9(INTERNAL_MPT_CONCAT9, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT10(A, B) INTERNAL_MPT_COMPOSE10(INTERNAL_MPT_CONCAT10, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT11(A, B) INTERNAL_MPT_COMPOSE11(INTERNAL_MPT_CONCAT11, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT12(A, B) INTERNAL_MPT_COMPOSE12(INTERNAL_MPT_CONCAT12, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT13(A, B) INTERNAL_MPT_COMPOSE13(INTERNAL_MPT_CONCAT13, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT14(A, B) INTERNAL_MPT_COMPOSE14(INTERNAL_MPT_CONCAT14, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT15(A, B) INTERNAL_MPT_COMPOSE15(INTERNAL_MPT_CONCAT15, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT16(A, B) INTERNAL_MPT_COMPOSE16(INTERNAL_MPT_CONCAT16, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT17(A, B) INTERNAL_MPT_COMPOSE17(INTERNAL_MPT_CONCAT17, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT18(A, B) INTERNAL_MPT_COMPOSE18(INTERNAL_MPT_CONCAT18, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT19(A, B) INTERNAL_MPT_COMPOSE19(INTERNAL_MPT_CONCAT19, (A, B))
#define INTERNAL_MPT_DELAYED_CONCAT20(A, B) INTERNAL_MPT_COMPOSE20(INTERNAL_MPT_CONCAT20, (A, B))

#define INTERNAL_MPT_SELECT( NAME, NUM ) INTERNAL_MPT_CONCAT( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT2( NAME, NUM ) INTERNAL_MPT_CONCAT2( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT3( NAME, NUM ) INTERNAL_MPT_CONCAT3( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT4( NAME, NUM ) INTERNAL_MPT_CONCAT4( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT5( NAME, NUM ) INTERNAL_MPT_CONCAT5( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT6( NAME, NUM ) INTERNAL_MPT_CONCAT6( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT7( NAME, NUM ) INTERNAL_MPT_CONCAT7( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT8( NAME, NUM ) INTERNAL_MPT_CONCAT8( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT9( NAME, NUM ) INTERNAL_MPT_CONCAT9( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT10( NAME, NUM ) INTERNAL_MPT_CONCAT10( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT11( NAME, NUM ) INTERNAL_MPT_CONCAT11( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT12( NAME, NUM ) INTERNAL_MPT_CONCAT12( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT13( NAME, NUM ) INTERNAL_MPT_CONCAT13( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT14( NAME, NUM ) INTERNAL_MPT_CONCAT14( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT15( NAME, NUM ) INTERNAL_MPT_CONCAT15( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT16( NAME, NUM ) INTERNAL_MPT_CONCAT16( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT17( NAME, NUM ) INTERNAL_MPT_CONCAT17( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT18( NAME, NUM ) INTERNAL_MPT_CONCAT18( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT19( NAME, NUM ) INTERNAL_MPT_CONCAT19( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT20( NAME, NUM ) INTERNAL_MPT_CONCAT20( NAME ## _, NUM )

#define INTERNAL_MPT_DELAYED_SELECT( NAME, NUM ) INTERNAL_MPT_SELECT( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT2( NAME, NUM ) INTERNAL_MPT_SELECT2( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT3( NAME, NUM ) INTERNAL_MPT_SELECT3( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT4( NAME, NUM ) INTERNAL_MPT_SELECT4( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT5( NAME, NUM ) INTERNAL_MPT_SELECT5( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT6( NAME, NUM ) INTERNAL_MPT_SELECT6( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT7( NAME, NUM ) INTERNAL_MPT_SELECT7( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT8( NAME, NUM ) INTERNAL_MPT_SELECT8( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT9( NAME, NUM ) INTERNAL_MPT_SELECT9( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT10( NAME, NUM ) INTERNAL_MPT_SELECT10( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT11( NAME, NUM ) INTERNAL_MPT_SELECT11( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT12( NAME, NUM ) INTERNAL_MPT_SELECT12( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT13( NAME, NUM ) INTERNAL_MPT_SELECT13( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT14( NAME, NUM ) INTERNAL_MPT_SELECT14( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT15( NAME, NUM ) INTERNAL_MPT_SELECT15( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT16( NAME, NUM ) INTERNAL_MPT_SELECT16( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT17( NAME, NUM ) INTERNAL_MPT_SELECT17( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT18( NAME, NUM ) INTERNAL_MPT_SELECT18( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT19( NAME, NUM ) INTERNAL_MPT_SELECT19( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT20( NAME, NUM ) INTERNAL_MPT_SELECT20( NAME, NUM )

#define INTERNAL_MPT_COMPOSE( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE2( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE3( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE4( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE5( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE6( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE7( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE8( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE9( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE10( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE11( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE12( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE13( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE14( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE15( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE16( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE17( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE18( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE19( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE20( macro, args ) macro args


#define INTERNAL_MPT_DELAYED_COMPOSE( macro, args ) INTERNAL_MPT_COMPOSE( macro, INTERNAL_MPT_DELAY(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE2( macro, args ) INTERNAL_MPT_COMPOSE2( macro, INTERNAL_MPT_DELAY2(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE3( macro, args ) INTERNAL_MPT_COMPOSE3( macro, INTERNAL_MPT_DELAY3(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE4( macro, args ) INTERNAL_MPT_COMPOSE4( macro, INTERNAL_MPT_DELAY4(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE5( macro, args ) INTERNAL_MPT_COMPOSE5( macro, INTERNAL_MPT_DELAY5(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE6( macro, args ) INTERNAL_MPT_COMPOSE6( macro, INTERNAL_MPT_DELAY6(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE7( macro, args ) INTERNAL_MPT_COMPOSE7( macro, INTERNAL_MPT_DELAY7(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE8( macro, args ) INTERNAL_MPT_COMPOSE8( macro, INTERNAL_MPT_DELAY8(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE9( macro, args ) INTERNAL_MPT_COMPOSE9( macro, INTERNAL_MPT_DELAY9(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE10( macro, args ) INTERNAL_MPT_COMPOSE10( macro, INTERNAL_MPT_DELAY10(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE11( macro, args ) INTERNAL_MPT_COMPOSE11( macro, INTERNAL_MPT_DELAY11(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE12( macro, args ) INTERNAL_MPT_COMPOSE12( macro, INTERNAL_MPT_DELAY12(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE13( macro, args ) INTERNAL_MPT_COMPOSE13( macro, INTERNAL_MPT_DELAY13(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE14( macro, args ) INTERNAL_MPT_COMPOSE14( macro, INTERNAL_MPT_DELAY14(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE15( macro, args ) INTERNAL_MPT_COMPOSE15( macro, INTERNAL_MPT_DELAY15(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE16( macro, args ) INTERNAL_MPT_COMPOSE16( macro, INTERNAL_MPT_DELAY16(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE17( macro, args ) INTERNAL_MPT_COMPOSE17( macro, INTERNAL_MPT_DELAY17(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE18( macro, args ) INTERNAL_MPT_COMPOSE18( macro, INTERNAL_MPT_DELAY18(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE19( macro, args ) INTERNAL_MPT_COMPOSE19( macro, INTERNAL_MPT_DELAY19(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE20( macro, args ) INTERNAL_MPT_COMPOSE20( macro, INTERNAL_MPT_DELAY20(args) )


#endif
