#ifndef MPT_MISCELLANEOUS_H
#define MPT_MISCELLANEOUS_H

#define MPT_CONCAT( A, B ) A ## B
#define MPT_COMPOSE( A, B ) A B
#define INTERNAL_MPT_REMOVE_PARENTHESIS( ... ) __VA_ARGS__

#define MPT_REMOVE_PARENTHESIS( ... ) INTERNAL_MPT_REMOVE_PARENTHESIS __VA_ARGS__

#endif