#ifndef MPT_MISCELLANEOUS_H
#define MPT_MISCELLANEOUS_H

#define MPT_CONCAT( A, B ) A ## B
#define MPT_CONCAT2( A, B ) A ## B
#define MPT_CONCAT3( A, B ) A ## B
#define MPT_CONCAT4( A, B ) A ## B
#define MPT_CONCAT5( A, B ) A ## B
#define MPT_CONCAT6( A, B ) A ## B
#define MPT_CONCAT7( A, B ) A ## B
#define MPT_CONCAT8( A, B ) A ## B
#define MPT_CONCAT9( A, B ) A ## B

#define MPT_COMPOSE( A, B ) A B
#define MPT_COMPOSE2( A, B ) A B
#define MPT_COMPOSE3( A, B ) A B
#define MPT_COMPOSE4( A, B ) A B
#define MPT_COMPOSE5( A, B ) A B
#define MPT_COMPOSE6( A, B ) A B
#define MPT_COMPOSE7( A, B ) A B
#define MPT_COMPOSE8( A, B ) A B
#define MPT_COMPOSE9( A, B ) A B

#define MPT_DELAYED_CONCAT(A, B) MPT_COMPOSE(MPT_CONCAT, (A, B))
#define MPT_DELAYED_CONCAT2(A, B) MPT_COMPOSE2(MPT_CONCAT2, (A, B))
#define MPT_DELAYED_CONCAT3(A, B) MPT_COMPOSE3(MPT_CONCAT3, (A, B))
#define MPT_DELAYED_CONCAT4(A, B) MPT_COMPOSE4(MPT_CONCAT4, (A, B))
#define MPT_DELAYED_CONCAT5(A, B) MPT_COMPOSE5(MPT_CONCAT5, (A, B))
#define MPT_DELAYED_CONCAT6(A, B) MPT_COMPOSE6(MPT_CONCAT6, (A, B))
#define MPT_DELAYED_CONCAT7(A, B) MPT_COMPOSE7(MPT_CONCAT7, (A, B))
#define MPT_DELAYED_CONCAT8(A, B) MPT_COMPOSE8(MPT_CONCAT8, (A, B))
#define MPT_DELAYED_CONCAT9(A, B) MPT_COMPOSE9(MPT_CONCAT9, (A, B))

#define INTERNAL_MPT_REMOVE_PARENTHESIS( ... ) __VA_ARGS__
#define MPT_REMOVE_PARENTHESIS( ... ) INTERNAL_MPT_REMOVE_PARENTHESIS __VA_ARGS__

#define INTERNAL_MPT_DELAY( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY2( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY3( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY4( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY5( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY7( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY8( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY9( ... ) __VA_ARGS__
#define INTERNAL_MPT_DELAY_ONE( x ) x

#define INTERNAL_MPT_CONCAT( A, B ) A ## B
#define INTERNAL_MPT_CONCAT2( A, B ) A ## B
#define INTERNAL_MPT_CONCAT3( A, B ) A ## B
#define INTERNAL_MPT_CONCAT4( A, B ) A ## B
#define INTERNAL_MPT_CONCAT5( A, B ) A ## B
#define INTERNAL_MPT_CONCAT6( A, B ) A ## B
#define INTERNAL_MPT_CONCAT7( A, B ) A ## B
#define INTERNAL_MPT_CONCAT8( A, B ) A ## B
#define INTERNAL_MPT_CONCAT9( A, B ) A ## B

#define INTERNAL_MPT_SELECT( NAME, NUM ) INTERNAL_MPT_CONCAT( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT2( NAME, NUM ) INTERNAL_MPT_CONCAT2( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT3( NAME, NUM ) INTERNAL_MPT_CONCAT3( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT4( NAME, NUM ) INTERNAL_MPT_CONCAT4( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT5( NAME, NUM ) INTERNAL_MPT_CONCAT5( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT6( NAME, NUM ) INTERNAL_MPT_CONCAT6( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT7( NAME, NUM ) INTERNAL_MPT_CONCAT7( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT8( NAME, NUM ) INTERNAL_MPT_CONCAT8( NAME ## _, NUM )
#define INTERNAL_MPT_SELECT9( NAME, NUM ) INTERNAL_MPT_CONCAT9( NAME ## _, NUM )

#define INTERNAL_MPT_DELAYED_SELECT( NAME, NUM ) INTERNAL_MPT_SELECT( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT2( NAME, NUM ) INTERNAL_MPT_SELECT2( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT3( NAME, NUM ) INTERNAL_MPT_SELECT3( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT4( NAME, NUM ) INTERNAL_MPT_SELECT4( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT5( NAME, NUM ) INTERNAL_MPT_SELECT5( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT6( NAME, NUM ) INTERNAL_MPT_SELECT6( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT7( NAME, NUM ) INTERNAL_MPT_SELECT7( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT8( NAME, NUM ) INTERNAL_MPT_SELECT8( NAME, NUM )
#define INTERNAL_MPT_DELAYED_SELECT9( NAME, NUM ) INTERNAL_MPT_SELECT9( NAME, NUM )

#define INTERNAL_MPT_COMPOSE( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE2( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE3( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE4( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE5( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE6( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE7( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE8( macro, args ) macro args
#define INTERNAL_MPT_COMPOSE9( macro, args ) macro args


#define INTERNAL_MPT_DELAYED_COMPOSE( macro, args ) INTERNAL_MPT_COMPOSE( macro, INTERNAL_MPT_DELAY(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE2( macro, args ) INTERNAL_MPT_COMPOSE2( macro, INTERNAL_MPT_DELAY2(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE3( macro, args ) INTERNAL_MPT_COMPOSE3( macro, INTERNAL_MPT_DELAY3(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE4( macro, args ) INTERNAL_MPT_COMPOSE4( macro, INTERNAL_MPT_DELAY4(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE5( macro, args ) INTERNAL_MPT_COMPOSE5( macro, INTERNAL_MPT_DELAY5(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE6( macro, args ) INTERNAL_MPT_COMPOSE6( macro, INTERNAL_MPT_DELAY6(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE7( macro, args ) INTERNAL_MPT_COMPOSE7( macro, INTERNAL_MPT_DELAY7(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE8( macro, args ) INTERNAL_MPT_COMPOSE8( macro, INTERNAL_MPT_DELAY8(args) )
#define INTERNAL_MPT_DELAYED_COMPOSE9( macro, args ) INTERNAL_MPT_COMPOSE9( macro, INTERNAL_MPT_DELAY9(args) )


#endif
